### PR TITLE
additional test & fixtures for fields option

### LINKED ISSUE #386: MsgDelegate amount should not be nullable
For some reason the `amount` field in the generated `MsgDelegate` is optional: https://github.com/confio/cosmjs-types/blob/v0.8.0/src/cosmos/staking/v1beta1/tx.ts#L36-L44

Hoewver, the protos from which is is generates have a `(gogoproto.nullable) = false` annotation:

```proto
// MsgDelegate defines a SDK message for performing a delegation of coins
// from a delegator to a validator.
message MsgDelegate {
  option (cosmos.msg.v1.signer) = "delegator_address";
  option (amino.name)           = "cosmos-sdk/MsgDelegate";

  option (gogoproto.equal)           = false;
  option (gogoproto.goproto_getters) = false;

  string                   delegator_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string                   validator_address = 2 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  cosmos.base.v1beta1.Coin amount            = 3 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];
}
```

In other places this annotation is considered, right? My expected output is

```diff
 export interface MsgDelegate {
   delegatorAddress: string;
   validatorAddress: string;
-  amount?: Coin;
+  amount: Coin;
 }
```

### PR DESCRIPTION
**Pull request by hoangdv2429**
Close #386

### CODE REVIEW

**Review by webmaster128 — APPROVED** [review]
Nice!

**Comment by hoangdv2429** [comment]
@pyramation Can you have a look at this PR sir, thank you!

**Comment by hoangdv2429** [comment]
I'm pushing a fix for grpc-gateway params and it contains fix for this one too so I'll merge this one for now @pyramation

**Comment by webmaster128** [comment]
Oh, it looks like this change breaks the tsc compilation: https://github.com/confio/cosmjs-types/pull/70

The reason is wthere is code like

```
function createBaseSimpleValidator(): SimpleValidator {
  return {
    pubKey: undefined,
    votingPower: Long.ZERO,
  };
}
```

but `pubKey` is now of type `pubKey: PublicKey;`

I think this can be solved by using 

```diff
diff --git a/src/tendermint/abci/types.ts b/src/tendermint/abci/types.ts
index e85efee..886c247 100644
--- a/src/tendermint/abci/types.ts
+++ b/src/tendermint/abci/types.ts
@@ -3891,7 +3891,7 @@ export const Validator = {
 };
 function createBaseValidatorUpdate(): ValidatorUpdate {
   return {
-    pubKey: undefined,
+    pubKey: PublicKey.fromPartial({}),
     power: Long.ZERO,
   };
 }
```

This is how the Go implementation would behave as well. There is an instance and this can always be a default instance with nothing set in protobuf.

**Comment by webmaster128** [comment]
Oh, it looks like this change breaks the tsc compilation: https://github.com/confio/cosmjs-types/pull/70

The reason is wthere is code like

```
function createBaseSimpleValidator(): SimpleValidator {
  return {
    pubKey: undefined,
    votingPower: Long.ZERO,
  };
}
```

but `pubKey` is now of type `pubKey: PublicKey;`

I think this can be solved by using 

```diff
diff --git a/src/tendermint/abci/types.ts b/src/tendermint/abci/types.ts
index e85efee..886c247 100644
--- a/src/tendermint/abci/types.ts
+++ b/src/tendermint/abci/types.ts
@@ -3891,7 +3891,7 @@ export const Validator = {
 };
 function createBaseValidatorUpdate(): ValidatorUpdate {
   return {
-    pubKey: undefined,
+    pubKey: PublicKey.fromPartial({}),
     power: Long.ZERO,
   };
 }
```

This is how the Go implementation would behave as well. There is an instance and this can always be a default instance with nothing set in protobuf.

**Comment by hoangdv2429** [comment]
Good morning sir @webmaster128 , I looked it up and it have been this way since first version so can you make another issue and I'll be working on it. Thank you sir!

**Comment by hoangdv2429** [comment]
@webmaster128 can you check the brand from this one https://github.com/osmosis-labs/telescope/pull/400 , it'll fix the above issue

**Pull request merged**
