### PR TITLE
feat/web-socket-client

### PR DESCRIPTION
**Pull request by hoangdv2429**
This PR is for creating web-socket client 
- [x] new utils for web socket
- [x] add new option for web socket client.
- [x] add new client template to clientFactory.
- [ ] a function to check/modify the url for web-socket (e.g: rpc.osmosis.zone => wss://rpc.osmosis.zone/websocket)
- [x] open/close connection function
- [x] a function that return message from server ( as Json )

### CODE REVIEW

**Comment by hoangdv2429** [comment]
Good morning, @Zetazzz! What do you think about the functions that I listed above? Do you think they are sufficient for now?

**Comment by hoangdv2429** [comment]
@Zetazzz that's great! Let's rock it 😆

**Comment by Zetazzz** [comment]
> @Zetazzz that's great! Let's rock it 😆

And there's one more thing, can you describe some stories when user's using our generated code, hopefully those user stories can cover most of the cases, if something's not sure yet, we can put a ? after it. Like:

users wanna use pre-generated events based on some files?
users wanna see there're several pre-set ws instances for every service(link), and users can access those instances by namespace.
For each service:
users also wanna subscribe queries by themselves.
users also wanna unsubscribe queries by themselves.
users also wanna unsubscribe all

**Comment by hoangdv2429** [comment]
@Zetazzz  I think we'll have to look at where we get all kind of events from the chain. I think that for each chain there will be (ofc base cosmos events) and then we'll have other chain custom module/event. creating a list of those events for each chain would be really useful for users I think. Also your suggest on each services is really good, I think we'll go with it first.

**Comment by hoangdv2429** [comment]
@Zetazzz hey, I did some research on events and here is what I found. we'll have two source for getting list of events https://docs.cosmos.network/v0.46/core/events.html

**Comment by hoangdv2429** [comment]
I think we should get all the typed events working first and then working on event.proto later on. wdyt @Zetazzz ?

**Comment by Zetazzz** [comment]
@hoangdv2429 Hi, I just checked in generator codes, I also fixed export in ast package, please make sure to get and merge the latest change! Thank you very much!

**Comment by Zetazzz** [comment]
Close this for now, since Websocket exists in cosmjs.

**Pull request closed without merging**
