### PR TITLE
glob files and protos

### PR DESCRIPTION
**Pull request by pyramation**

### CODE REVIEW

**Comment by pyramation** [comment]
hey @Zetazzz can you check if we use `isRefIncluded` everywhere we need? In other words, we should make sure we're not directly checking `ref.protos` or `ref.packages` arrays for `includes()` or looping through and directly checking equality. 

If we can verify we're using `isRefIncluded` then this should theoretically work. And then eventually, we should deprecate the `patterns` array

**Comment by Zetazzz** [comment]
Checked. There're three places we're having include checks of patterns, packages and protos: react-query, mobx, pinia. All of them are using isRefIncluded.
I also noticed that there're some other scope checking that's not using isRefIncluded check, not sure this's just another story or we should also handle them:
patterns: 
    tsDisable
    eslintDisable

packages:
    aggregatedLCD
    lcdClients
    rpcClients

**Comment by pyramation** [comment]
> Checked. There're three places we're having include checks of patterns, packages and protos: react-query, mobx, pinia. All of them are using isRefIncluded. I also noticed that there're some other scope checking that's not using isRefIncluded check, not sure this's just another story or we should also handle them: 

Great! thanks for looking

> patterns: tsDisable eslintDisable

let's leave `patterns` in these two

> packages: aggregatedLCD lcdClients rpcClients

Let's update these — they should support the same interface (protos, packages), right?

**Comment by Zetazzz** [comment]
Hi, yes, I think so. I'll try to make the change.

**Comment by Zetazzz** [comment]
for scoped lcd and rpc clients, currently we can't add protos check.

        return {
            // TODO use this to build LCD aggregators with scopes
            package: c.ref.proto.package,
            localname,
            filename
        };

    }).filter(Boolean);

    bundler.addLCDClients(lcdClients);

since proto info wasn't pushed into the clients array.
If we have to check protos at least we have to add corresponding proto file name to the array.
Should we add the file name?

**Comment by Zetazzz** [comment]
I've got both isRefIncluded and isRefExcluded done and tested, please review

**Pull request merged**
