### PR TITLE
feat: Add --config option for JSON to cli

### PR DESCRIPTION
**Pull request by clockworkgr**
Adds the ability to provide options via JSON with a `--config` arg.

Read code comments for details.

Fixes: https://github.com/osmosis-labs/telescope/issues/351

### CODE REVIEW

**Comment by pyramation** [comment]
this is cool, but it makes it so the interactive CLI will always prompt the user for the config object. Can you add something like this:

instead of calling `await prompt()`, simply check if `argv.config` is set? This will make it optional so it's not prompting the user for the config which may confuse people as it's more advanced and requires a path to a file.

**Comment by clockworkgr** [comment]
> this is cool, but it makes it so the interactive CLI will always prompt the user for the config object. Can you add something like this:
> 
> instead of calling `await prompt()`, simply check if `argv.config` is set? This will make it optional so it's not prompting the user for the config which may confuse people as it's more advanced and requires a path to a file. Then make everything inside of this if statement, so it's only called when `argv.config` is set

Sorry for the delayed response...I missed the notification for your reply :)

I saw that Interactive CLI wrote out the config file post-interactive prompts and thought it might as well be configurable (hence the prompt)

We could just as well stick with the hardcoded `.telescope.json` and get rid of the prompt altogether.

**Comment by pyramation** [comment]
hey @Zetazzz let's review this — I think there are some small changes we need to make so I'll make a feature branch for this one

**Comment by pyramation** [comment]
moved here #390

**Pull request merged**
